var aData = {
    aST_Li:[
        {
            sImg:"img/imgs1/fo1.ico",
            title:"高速浏览器1"
        },
        {
            sImg:"img/imgs1/fo2.ico",
            title:"高速浏览器2"
        },
        {
            sImg:"img/imgs1/fo3.ico",
            title:"高速浏览器3"
        },
        {
            sImg:"img/imgs1/fo4.ico",
            title:"高速浏览器4"
        },
        {
            sImg:"img/imgs1/fo5.ico",
            title:"高速浏览器5"
        },
        {
            sImg:"img/imgs1/fo6.ico",
            title:"高速浏览器6"
        },
        {
            sImg:"img/imgs1/fo7.ico",
            title:"高速浏览器7"
        },
        {
            sImg:"img/imgs1/fo8.ico",
            title:"高速浏览器8"
        },
        {
            sImg:"img/imgs1/fo9.ico",
            title:"高速浏览器9"
        },
        {
            sImg:"img/imgs1/fo10.ico",
            title:"高速浏览器10"
        },
        {
            sImg:"img/imgs1/fo11.ico",
            title:"高速浏览器11"
        },
        {
            sImg:"img/imgs1/fo12.ico",
            title:"高速浏览器12"
        }

    ],
    aFile:[
        {
            pId:0,
            mId:1,
            title:"我的电脑",
            fImg:"img/7270.ico"
        },
        {
            pId:0,
            mId:2,
            title:"我的设备",
            fImg:"img/7263.ico"
        },
        {
            pId:0,
            mId:3,
            title:"回收站",
            fImg:"img/7262.ico"
        },
        {
            pId:0,
            mId:4,
            title:"我的图片",
            fImg:"img/7267.ico"
        },
        {
            pId:0,
            title:"新建文件夹",
            fImg:"img/folder.png"
        },
        {
            pId:1,
            title:"新建文件夹",
            fImg:"img/folder.png"
        },
    ]
};